Update
Now uses unique name

diff --git a/recycler b/recycler
--- a/recycler
+++ b/recycler
@@ -76,35 +76,34 @@ list_files() {
 # Restore files
 restore_files() {
     if [ $# -eq 0 ]; then
-        echo "Error: No files specified for restoration"
-        echo "Usage: $(basename "$0") -r <file1> [file2] ..."
+        echo "Error: No unique name specified for restoration"
+        echo "Usage: $(basename "$0") -r <unique_name>"
         exit 1
     fi
 
     init_recycler
     
-    target=$1
-    entry=$(grep -F "/${target}" "$RECYCLE_INFO" | tail -n 1)
+    unique_name=$1
+    entry=$(grep -F "${unique_name}" "$RECYCLE_INFO")
+    echo $entry
     if [ -z "$entry" ]; then
-            echo "Error: '$target' not found in recycle bin"
-            exit
+        echo "Error: Unique name '$unique_name' not found in recycle bin"
+        exit 1
     fi
-        
-    unique_name=$(echo "$entry" | cut -d: -f1)
+    
     original_path=$(echo "$entry" | cut -d: -f2)
-        
+    
     dir_path=$(dirname "$original_path")
     if [ ! -d "$dir_path" ]; then
         mkdir -p "$dir_path"
     fi
-        
+    
     if mv "$RECYCLE_BIN/$unique_name" "$original_path"; then
         sed -i "\:^$unique_name\::d" "$RECYCLE_INFO"
-        echo "Restored '$target' to original location"
+        echo "Restored '$unique_name' to original location: $original_path"
     else
-        echo "Error restoring '$target'"
+        echo "Error restoring '$unique_name'"
     fi
-    
 }
 
 # Empty recycle bin
